---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: sas-postgres-config
behavior: merge
literals:
  - DATABASE_HOST={{ V4_CFG_POSTGRES_SERVERS.default.fqdn }}
  - DATABASE_PORT={{ V4_CFG_POSTGRES_SERVERS.default.server_port }}
  - DATABASE_SSL_ENABLED="{{ V4_CFG_POSTGRES_SERVERS.default.ssl_enforcement_enabled|bool|lower }}"
  - DATABASE_NAME={{ V4_CFG_POSTGRES_SERVERS.default.database|default('SharedServices', true) }}
  - EXTERNAL_DATABASE="true"
  - SAS_DATABASE_DATABASESERVERNAME="postgres"
